export const GET_CUSTOMERS_REQUEST = 'GET_CUSTOMERS_REQUEST';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAILURE = 'GET_CUSTOMERS_FAILURE';

export const REGISTER_CUSTOMERS_REQUEST = 'REGISTER_CUSTOMERS_REQUEST';
export const REGISTER_CUSTOMERS_SUCCESS = 'REGISTER_CUSTOMERS_SUCCESS';
export const REGISTER_CUSTOMERS_FAILURE = 'REGISTER_CUSTOMERS_FAILURE';

export const GET_CUSTOMER_HASH_REQUEST = 'GET_CUSTOMER_HASH_REQUEST';
export const GET_CUSTOMER_HASH_SUCCESS = 'GET_CUSTOMER_HASH_SUCCESS';
export const GET_CUSTOMER_HASH_FAILURE = 'GET_CUSTOMER_HASH_FAILURE';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
export const RESET_CUSTOMER_REGISTRATION = 'RESET_CUSTOMER_REGISTRATION';
