/* General */
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

/* Customers */
export const GET_CUSTOMERS_REQUEST = 'GET_CUSTOMERS_REQUEST';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAILURE = 'GET_CUSTOMERS_FAILURE';

export const GET_CUSTOMER_BY_CLAVE_REQUEST = 'GET_CUSTOMER_BY_CLAVE_REQUEST';
export const GET_CUSTOMER_BY_CLAVE_SUCCESS = 'GET_CUSTOMER_BY_CLAVE_SUCCESS';
export const GET_CUSTOMER_BY_CLAVE_FAILURE = 'GET_CUSTOMER_BY_CLAVE_FAILURE';

export const ADD_CUSTOMER_REQUEST = 'ADD_CUSTOMER_REQUEST';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_FAILURE = 'ADD_CUSTOMER_FAILURE';

export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE';

export const GET_CUSTOMER_HASH_REQUEST = 'GET_CUSTOMER_HASH_REQUEST';
export const GET_CUSTOMER_HASH_SUCCESS = 'GET_CUSTOMER_HASH_SUCCESS';
export const GET_CUSTOMER_HASH_FAILURE = 'GET_CUSTOMER_HASH_FAILURE';

export const RESET_ADD_CUSTOMER_STATE = 'RESET_ADD_CUSTOMER_STATE';
export const RESET_UPDATE_CUSTOMER_STATE = 'RESET_UPDATE_CUSTOMER_STATE';

/* Items */
export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';

export const GET_ITEM_BY_CLAVE_REQUEST = 'GET_ITEM_BY_CLAVE_REQUEST';
export const GET_ITEM_BY_CLAVE_SUCCESS = 'GET_ITEM_BY_CLAVE_SUCCESS';
export const GET_ITEM_BY_CLAVE_FAILURE = 'GET_ITEM_BY_CLAVE_FAILURE';

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';

export const GET_ITEM_HASH_REQUEST = 'GET_ITEM_HASH_REQUEST';
export const GET_ITEM_HASH_SUCCESS = 'GET_ITEM_HASH_SUCCESS';
export const GET_ITEM_HASH_FAILURE = 'GET_ITEM_HASH_FAILURE';

export const RESET_ADD_ITEM_STATE = 'RESET_ADD_ITEM_STATE';
export const RESET_UPDATE_ITEM_STATE = 'RESET_UPDATE_ITEM_STATE';

/* Configuration */
export const GET_CONFIGURATION_REQUEST = 'GET_CONFIGURATION_REQUEST';
export const GET_CONFIGURATION_SUCCESS = 'GET_CONFIGURATION_SUCCESS';
export const GET_CONFIGURATION_FAILURE = 'GET_CONFIGURATION_FAILURE';

export const CREATE_CONFIGURATION_REQUEST = 'CREATE_CONFIGURATION_REQUEST';
export const CREATE_CONFIGURATION_SUCCESS = 'CREATE_CONFIGURATION_SUCCESS';
export const CREATE_CONFIGURATION_FAILURE = 'CREATE_CONFIGURATION_FAILURE';

export const UPDATE_CONFIGURATION_REQUEST = 'UPDATE_CONFIGURATION_REQUEST';
export const UPDATE_CONFIGURATION_SUCCESS = 'UPDATE_CONFIGURATION_SUCCESS';
export const UPDATE_CONFIGURATION_FAILURE = 'UPDATE_CONFIGURATION_FAILURE';

export const RESET_CONFIGURATION = 'RESET_CONFIGURATION';
